<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ac41322e-c3a9-4c5c-9c9a-e4801d10be02</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrkAutomacao.Application\BrkAutomacao.Application.csproj" />
    <ProjectReference Include="..\BrkAutomacao.Infrastructure\BrkAutomacao.Infrastructure.csproj" />
  </ItemGroup>

</Project>
